<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >


    
    <!-- Vehicle Geometries -->
    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_separation" value="0.253" />

    <xacro:include filename="inertial_macros.xacro"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="grey">
        <color rgba="0.2 0.2 0.2 1.0"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">
    </link>


    <!-- BASE_FOOTPRINT LINK-->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>
    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0.0545 0.0 0.0723" rpy="1.57 0 1.57"/>
    </joint>
    <link name="chassis">
        <visual>
            <geometry>
                <mesh filename="package://sobot_gazebo/description/meshes/sobot_chassis.dae" scale="1 1 1"/> 
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://sobot_gazebo/description/meshes/sobot_chassis.dae" scale="1 1 1"/> 
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.292" y="0.420" z="0.25">
            <origin xyz="0.0 0.0723 -0.2" rpy="1.57 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <mu1 value="0.01"/>
        <mu2 value="0.01"/>
    </gazebo>
    
    <!-- LEFT WHEEL LINK -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0.0105  ${wheel_separation/2} 0.05" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

    <link name="left_wheel">
        <visual>
                <origin xyz="0.0 0.0 0.0" rpy="-1.57 0 0" />
            <geometry>
                <mesh filename="package://sobot_gazebo/description/meshes/sobot_wheel.dae" scale="1 1 1"/> <!-- Colocar o arquivo STL-->
            </geometry>
        </visual>
        <collision>
                <origin xyz="0.0 0.0 0.0" rpy="-1.57 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="0.01"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.01" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- RIGHT WHEEL LINK -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0.0105 ${-wheel_separation/2} 0.05" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0 0" />
            <geometry>
                <mesh filename="package://sobot_gazebo/description/meshes/sobot_wheel.dae" scale="1 1 1"/> <!-- Colocar o arquivo STL-->
            </geometry>
        </visual>
        <collision>
                        <origin xyz="0.0 0.0 0.0" rpy="1.57 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="0.01"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.01" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
</robot>